# docker-compose up -d --build

version: "3.7"
services:
  client:
    container_name: react-ski-climbing-shop-back-end
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 5000
